
package async.ws.notifier.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotifierImplService", targetNamespace = "http://service.notifier.ws.async/", wsdlLocation = "file:/media/juan/DATA/linux/sistemas-distribuidos/push-notification/client/src/main/java/notifier.wsdl")
public class NotifierImplService
    extends Service
{

    private final static URL NOTIFIERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFIERIMPLSERVICE_EXCEPTION;
    private final static QName NOTIFIERIMPLSERVICE_QNAME = new QName("http://service.notifier.ws.async/", "NotifierImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/sistemas-distribuidos/push-notification/client/src/main/java/notifier.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFIERIMPLSERVICE_WSDL_LOCATION = url;
        NOTIFIERIMPLSERVICE_EXCEPTION = e;
    }

    public NotifierImplService() {
        super(__getWsdlLocation(), NOTIFIERIMPLSERVICE_QNAME);
    }

    public NotifierImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFIERIMPLSERVICE_QNAME, features);
    }

    public NotifierImplService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFIERIMPLSERVICE_QNAME);
    }

    public NotifierImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFIERIMPLSERVICE_QNAME, features);
    }

    public NotifierImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotifierImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Notifier
     */
    @WebEndpoint(name = "NotifierImplPort")
    public Notifier getNotifierImplPort() {
        return super.getPort(new QName("http://service.notifier.ws.async/", "NotifierImplPort"), Notifier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notifier
     */
    @WebEndpoint(name = "NotifierImplPort")
    public Notifier getNotifierImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.notifier.ws.async/", "NotifierImplPort"), Notifier.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFIERIMPLSERVICE_EXCEPTION!= null) {
            throw NOTIFIERIMPLSERVICE_EXCEPTION;
        }
        return NOTIFIERIMPLSERVICE_WSDL_LOCATION;
    }

}
