
package async.ws.server.service;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://service.server.ws.async/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "request", targetNamespace = "http://service.server.ws.async/", className = "async.ws.server.service.Request")
    @Action(input = "http://service.server.ws.async/Server/request")
    public void request(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registry", targetNamespace = "http://service.server.ws.async/", className = "async.ws.server.service.Registry")
    @ResponseWrapper(localName = "registryResponse", targetNamespace = "http://service.server.ws.async/", className = "async.ws.server.service.RegistryResponse")
    @Action(input = "http://service.server.ws.async/Server/registryRequest", output = "http://service.server.ws.async/Server/registryResponse")
    public int registry();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "response", targetNamespace = "http://service.server.ws.async/", className = "async.ws.server.service.Response")
    @ResponseWrapper(localName = "responseResponse", targetNamespace = "http://service.server.ws.async/", className = "async.ws.server.service.ResponseResponse")
    @Action(input = "http://service.server.ws.async/Server/responseRequest", output = "http://service.server.ws.async/Server/responseResponse")
    public String response(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
